version: '3'

services:

  dotnet:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./proj_x:/proj_x
    ports:
      - "8020:8020"
    command: >
      bash -c "export DOTNET_ROOT=/dotnet-sdk && export PATH=/dotnet-sdk && dotnet watch --project . run --urls 'http://0.0.0.0:8020/'"

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network
  
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge