version: '3'

services:

  dotnet:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./proj_x:/proj_x
    ports:
      - "8020:8020"
    command: >
      bash -c "export DOTNET_ROOT=/dotnet-sdk && export PATH=/dotnet-sdk && dotnet watch --project . run --urls 'http://0.0.0.0:8020/'"