FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
curl \
wget \
unzip \
libicu-dev

COPY ./dotnet-sdk /dotnet-sdk
COPY ./scr-my /scr-my

RUN /scr-my/export4bash.sh

WORKDIR /proj_x

EXPOSE 8020